name: Defining CI pipeline /workflow for the solar system project
on: 
 push:
   branches:
     - main
     - 'feature/*'
   
 pull_request:
    branches: [main]

 workflow_dispatch:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.mongousername}}
  MONGO_PASSWORD: ${{secrets.MONGOPASSWORD}}
   
jobs:
  unit-testing:
    name: unit testing
    strategy:
      matrix:
        os: [ubuntu-latest]
        nodejs_version: [20]
    runs-on: ${{matrix.os}}
    container:
      image: node:20
    steps:
      - name: checkout repository
        id: unit_test_repo_checkout
        uses: actions/checkout@v4
      #- name: Install nodejs
       # id: nodejs_install_unit_test
       # uses: actions/setup-node@v4
       # with:
       #   node-version: ${{matrix.nodejs_version}}
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
      - name: insall NPM and test 
        id: nodejs_dependency_unit_test
        run: |
             npm install
             npm test
      - name: Download unit test report
        if: always()
        id: unit_test_report
        uses: actions/upload-artifact@v4
        with:
          name: felicia-test-result-${{matrix.nodejs_version}}-${{matrix.os}}
          path: test-results.xml
  code-coverage:
    name: code coverage of the unit test
    needs: [unit-testing]
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        id: code_coverage_repo_checkout
        uses: actions/checkout@v4
      - name: install nodejs for code coverage
        id: nodejs_setup_code_coverage
        uses: actions/setup-node@v4
      - name: cache the dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
      - name: install nodejs dependency
        id: install_npm_code_coverage
        run: npm install
      - name: Run code coverage
        continue-on-error: true
        id: run_code_coverage
        run: npm run coverage
      - name: upload test coverage
        id: upload_test_coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-result-felicia
          path: coverage
          retention-days: 2
  Docker:
    name: Containerization
    needs: [unit-testing,code-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: reposotory checkout
        id: repository_checout_deocker
        uses: actions/checkout@v4
      - name: Docker hub login
        id: docker_hub_login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{vars.DOCKER_LOGIN_USERNAME}}
          password: ${{secrets.DOCKER_LOGIN_PASSWORD}}
      - name: Docker Build 
        id: Docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{vars.DOCKER_LOGIN_USERNAME}}/solar-system:${{github.sha}}
      - name: Docker Image test
        id: docker_image_test
        continue-on-error: true
        run: |
             docker run --name "felicia-solar" -p 3000:3000 -d \ 
             -e MONGO_URI=$MONGO_URI \
             -e MONGO_USERNAME=$MONGO_USERNAME \
             -e MONGO_PASSWORD=$MONGO_PASSWORD \
             ${{vars.DOCKER_LOGIN_USERNAME}}/solar-system:${{github.sha}} \

             echo testing the image
             wget -q -o - 127.0.0.1:3000/live | grep live
      - name: Docker image push
        id: Docker_image_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true 
          tags: ${{vars.DOCKER_LOGIN_USERNAME}}/solar-system:${{github.sha}}
  Github_registry:
    name: Containerization using GHCR
    permissions: 
      packages: write

    needs: [unit-testing,code-coverage,Docker]
    runs-on: ubuntu-latest
    steps:
      - name: reposotory checkout
        id: repository_checout_deocker
        uses: actions/checkout@v4
      - name: Github registry login
        id: Github_registry_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set lowercase repository owner
        id: set_lowercase_owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Github container Build and push
        id: Github_container_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{env.REPO_OWNER_LOWERCASE}}/solar-system:${{github.sha}}
      
      
      


   
          
        
         
      