name: Defining CI pipeline /workflow for the solar system project
on: 
 push:
   branches:
     - main
     - 'feature/*'
   
 pull_request:
    branches: [main]

 workflow_dispatch:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.mongousername}}
  MONGO_PASSWORD: ${{secrets.MONGOPASSWORD}}
   
jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: insall NPM and test 
        run: |
             npm install
             npm test
      - name: Download the unit test report
        uses: actions/upload-artifact@v1
        with:
          name: unit test report
          path: test-results.xml
          
        
         
      